### PR TITLE
Make respondOn mainThread default for all sync rx call

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by secondsun** [comment]
If you are having an opinion about what the response thread is then we should make sure that we add javadocs.  It would be frustrating for a developer if they got a network on main thread exception because they chained a method off this.

**Comment by danielpassos** [comment]
@secondsun +1 but it `respondOn` can be changed by the developer right? ;)

**Comment by wtrocki** [comment]
@danielpassos This is actually really good question.

**Comment by secondsun** [comment]
@wtrocki @danielpassos  Yes it can always be changed, responses are build by using proxies.  So you will have the response call a proxy which will run on the main thread which will immediately call a proxy which will run on the thread the user wants.

**Pull request merged**
