### PR TITLE
Fix failing integration test

### PR DESCRIPTION
**Pull request by aidenkeating**
## Motivation

Currently integration tests are failing with an SSL Handshake error.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@danielpassos @secondsun  Jenkins seems to have stalled because of the `test/integration` label. Do you have any issue with me adding the integration tests as part of the CircleCI build? They're pretty quick at the moment and only require `mockable.io` to be accessible

**Comment by danielpassos** [comment]
@aidenkeating I'm -1 for having integration test on circle-ci. I know this is really fast for now, but Integration tests usually use an emulator and it takes a lot of time. Let's raise it on ML

**Comment by grdryn** [comment]
@psturc there's a Jenkinsfile for this repo, and for this PR there's a build that's stuck because of a label of `jenkins-openshift` not matching anything in Jenkins, from this line: https://github.com/aerogear/aerogear-android-sdk/blob/master/Jenkinsfile#L20 I think what you want is probably just the label `openshift`, is it?

**Comment by psturc** [comment]
@grdryn yes, thanks for letting me know! fixed here https://github.com/aerogear/aerogear-android-sdk/pull/239

**Pull request merged**
